# Gimli by Shanaka Dias
#              _.-;-._
#             ;_.JL___;
#             F"-/\_-7L
#             | a/ e | \
#            ,L,c;,.='/;,
#         _,-;;S:;:S;;:' '--._
#        ;. \;;s:::s;;: .'   /\
#       /  \  ;::::;;  /    /  \
#      / ,  k ;S';;'S.'    j __,l
#   ,---/| /  /S   /S '.   |'   ;
#  ,Ljjj |/|.' s .' s   \  L    |
#  LL,_ ]( \    /    '.  '.||   ;
#  ||\ > /  ;-.'_.-.___\.-'(|=="(
#  JJ," /   |_  [   ]     _]|   /
#   LL\/   ,' '--'-'-----'  \  (
#   ||     ;      |          |  >
#   JJ     |      |\         |,/
#    LL    |      ||       ' |
#    ||    |      ||       . |
#    JJ    /_     ||       ;_|
#     LL   L "==='|i======='_|
#     ||    i----' '-------';
#     JJ    ';-----.------,-'
#      LL     L_.__J,'---;'
#      ||      |   ,|    (
#      JJ     .'=  (|  ,_|
#       LL   /    .'L_    \
# snd   ||   '---'    '.___>
---
version: v1

labels:
  - label: "minor"
    sync: true
    matcher:
      title: ".*feat: .*"

  - label: "patch"
    sync: true
    matcher:
      title: ".*fix: .*"

  - label: "chore"
    sync: true
    matcher:
      title: ".*chore: .*"

  - label: "major"
    sync: true
    matcher:
      body: "(\\n|.)*BREAKING CHANGE(S|): (\\n|.)*"
      commmits: "(\\n|.)*BREAKING CHANGE(S|): (\\n|.)*"
      comment: "(\\n|.)*BREAKING CHANGE(S|): (\\n|.)*"

  - label: "attention 🚨"
    sync: true
    matcher:
      files:
        any: ["src/**", "**/src/**"]
        count:
          neq: 1

  - label: "type: feature ✨"
    sync: true
    matcher:
      body: "(\\n|.)*/feat(\\n|.)*"

  - label: "type: documentation 📝"
    sync: true
    matcher:
      body: "(\\n|.)*/docs(\\n|.)*"

  - label: "type: fix 🩹"
    sync: true
    matcher:
      body: "(\\n|.)*/fix(\\n|.)*"

  - label: "type: hotfix 🚑"
    sync: true
    matcher:
      body: "(\\n|.)*/hf (\\n|.)*"

  - label: "type: infrastructure 🧱"
    sync: true
    matcher:
      body: "(\\n|.)*/infra(\\n|.)*"

  - label: "type: security 🔒"
    sync: true
    matcher:
      body: "(\\n|.)*/sec (\\n|.)*"

  - label: "type: bug 🐛"
    sync: true
    matcher:
      body: "(\\n|.)*/bug(\\n|.)*"

  - label: "type: testing 🔎"
    sync: true
    matcher:
      body: "(\\n|.)*/test(\\n|.)*"

  - label: "type: improvement ⚡️"
    sync: true
    matcher:
      body: "(\\n|.)*/imp(\\n|.)*"

  - label: "type: dx 👩🏼‍💻"
    sync: true
    matcher:
      body: "(\\n|.)*/dx(\\n|.)*"

  - label: "type: ci/cd 👷🏾"
    sync: true
    matcher:
      body: "(\\n|.)*/ci(\\n|.)*"

  - label: "type: question 🤷🏽‍♀️"
    sync: true
    matcher:
      body: "(\\n|.)*/q (\\n|.)*"

  - label: "work: clear 🥱"
    sync: true
    matcher:
      body: "(\\n|.)*/clear(\\n|.)*"

  - label: "work: chaotic 😱"
    sync: true
    matcher:
      body: "(\\n|.)*/chaotic(\\n|.)*"

  - label: "work: complicated 😬"
    sync: true
    matcher:
      body: "(\\n|.)*/complicated(\\n|.)*"

  - label: "work: complex 😳"
    sync: true
    matcher:
      body: "(\\n|.)*/complex(\\n|.)*"

  - label: "effort: 1️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/1 (\\n|.)*"

  - label: "effort: 2️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/2(\\n|.)*"

  - label: "effort: 3️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/3(\\n|.)*"

  - label: "effort: 5️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/5(\\n|.)*"

  - label: "effort: 8️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/8(\\n|.)*"

  - label: "effort: 1️⃣3️⃣"
    sync: true
    matcher:
      body: "(\\n|.)*/13(\\n|.)*"
